### ISSUE TITLE
Installing the extension

### ISSUE THREAD

**Issue by goncaloGIT** [EUDAT-B2FIND/ckanext-b2find#11]
Hello

Im having some trouble making this extension work properly.
I followed the procedure on ckan documentation.
• git clone https://github.com/EUDAT-B2FIND/ckanext-b2find.git
• cd /root/ckanext-b2find
•  python setup.py install
• sudo service apache2 restart ; sudo service nginx restart;
• vim /etc/ckan/default/production.ini
• And edit the following line        ckan.plugins = stats text_view image_view recline_view b2find

And i got this

![image](https://cloud.githubusercontent.com/assets/25826516/26359594/ce16f854-3fcd-11e7-8301-af4791971b43.png)

Am i missing anything? Got no error's on my  /var/log/apache2/ckan_default.error.log

Here's some information about my envoriment:

SO: Ubuntu 14.4 LTS
CKAN: 2.5

Ty

Best Regards 
Gonçalo Barata

**Comment by goncaloGIT** [comment]
Solution to this problem.

  
  cp -R /root/ckanext-b2find/src/ckanext-b2find/ /usr/lib/ckan/default/src/
  source /usr/lib/ckan/default/bin/activate
  cd /usr/lib/ckan/default/src/ckanext-b2find/
  python setup.py develop
  service apache2 stop
  service apache2 start

**Comment by noumar** [comment]
Hi Gonçalo,

Great that you found the solution to your problem. CKAN is very well documented at http://docs.ckan.org/. So you can find answers to most things from there. Extensions are more preciously documented in http://docs.ckan.org/en/latest/extensions/.

If you have any problems with the extension itself let us know. And if you want to contribute something please feel free to create a pull request.

Thanks.
